const ST = {
  app: { fontFamily: "'Segoe UI','Helvetica Neue',sans-serif", background: "#0a0a0f", color: "#e0e0e0", minHeight: "100vh" },
  main: { maxWidth: 1400, margin: "0 auto", padding: "24px" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))", gap: 20 },
  btn: { background: "linear-gradient(135deg,#8B5CF6,#EC4899)", border: "none", borderRadius: 6, padding: "8px 16px", color: "#fff", cursor: "pointer", fontSize: 12, fontWeight: 700 },
  btnSec: { background: "#1e1e3a", border: "none", borderRadius: 6, padding: "8px 16px", color: "#888", cursor: "pointer", fontSize: 12 },
  modal: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.8)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200, padding: 20 },
  mContent: { background: "#16162a", borderRadius: 16, padding: 32, maxWidth: 600, width: "100%", maxHeight: "85vh", overflowY: "auto", border: "1px solid #2a2a4a" },
  input: { width: "100%", padding: "10px 14px", borderRadius: 8, border: "1px solid #2a2a4a", background: "#0d0d14", color: "#fff", fontSize: 14, outline: "none", marginBottom: 12, boxSizing: "border-box" },
  select: { width: "100%", padding: "10px 14px", borderRadius: 8, border: "1px solid #2a2a4a", background: "#0d0d14", color: "#fff", fontSize: 14, outline: "none", marginBottom: 12, boxSizing: "border-box" },
  label: { fontSize: 12, fontWeight: 700, color: "#888", marginBottom: 4, display: "block", textTransform: "uppercase", letterSpacing: 1 },
  header: { background: "linear-gradient(135deg,#0d0d14,#141422)", borderBottom: "1px solid #1e1e3a", position: "sticky", top: 0, zIndex: 100 },
  headerTop: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 24px", maxWidth: 1400, margin: "0 auto", flexWrap: "wrap", gap: 8 },
  logo: { fontSize: 26, fontWeight: 900, background: "linear-gradient(135deg,#8B5CF6,#EC4899)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", cursor: "pointer", letterSpacing: -1 },
  searchBox: { flex: 1, maxWidth: 500, margin: "0 24px", position: "relative" },
  searchInput: { width: "100%", padding: "10px 16px 10px 40px", borderRadius: 8, border: "1px solid #2a2a4a", background: "#12121f", color: "#fff", fontSize: 14, outline: "none", boxSizing: "border-box" },
  nav: { display: "flex", gap: 0, padding: "0 24px", maxWidth: 1400, margin: "0 auto", borderTop: "1px solid #1a1a30", flexWrap: "wrap" },
  navItem: { padding: "10px 20px", cursor: "pointer", fontSize: 13, fontWeight: 600, borderBottom: "2px solid transparent", transition: "all 0.2s" },
  navActive: { borderBottomColor: "#8B5CF6", color: "#8B5CF6" },
  hero: { background: "linear-gradient(135deg,#0d0d14,#1a0a2e 50%,#0d1b2a)", padding: "60px 24px", textAlign: "center", position: "relative", overflow: "hidden" },
  card: { background: "#12121f", borderRadius: 12, overflow: "hidden", border: "1px solid #1e1e3a", transition: "all 0.3s", cursor: "pointer" },
  cardImg: { width: "100%", height: 180, objectFit: "cover", borderBottom: "1px solid #1e1e3a" },
  cardBody: { padding: 16 },
  btnDanger: { background: "none", border: "1px solid #e74c3c", borderRadius: 8, padding: "6px 10px", color: "#e74c3c", cursor: "pointer", fontSize: 12 },
  textarea: { width: "100%", padding: "10px 14px", borderRadius: 8, border: "1px solid #2a2a4a", background: "#0d0d14", color: "#fff", fontSize: 14, outline: "none", marginBottom: 12, boxSizing: "border-box", minHeight: 100, resize: "vertical" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 },
  th: { padding: "12px 16px", textAlign: "left", borderBottom: "2px solid #2a2a4a", color: "#888", fontWeight: 700, fontSize: 11, textTransform: "uppercase", letterSpacing: 1 },
  td: { padding: "12px 16px", borderBottom: "1px solid #1a1a30" },
  sidebar: { width: 220, background: "#0d0d14", borderRight: "1px solid #1e1e3a", padding: "20px 0", minHeight: "calc(100vh - 100px)" },
  sideItem: { padding: "12px 24px", cursor: "pointer", fontSize: 13, fontWeight: 600, display: "flex", alignItems: "center", gap: 10, borderLeft: "3px solid transparent" },
  sideActive: { background: "#12121f", borderLeftColor: "#8B5CF6", color: "#8B5CF6" },
  stat: { background: "#12121f", borderRadius: 12, padding: 20, border: "1px solid #1e1e3a", textAlign: "center" },
  footer: { background: "#0a0a0f", borderTop: "1px solid #1e1e3a", padding: "40px 24px", marginTop: 60 },
  footerInner: { maxWidth: 1400, margin: "0 auto", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: 30 },
  error: { background: "#c0392b22", border: "1px solid #c0392b", borderRadius: 8, padding: "8px 12px", marginBottom: 16, color: "#e74c3c", fontSize: 13 },
  warning: { background: "#f39c1222", border: "1px solid #f39c1244", borderRadius: 8, padding: "8px 16px", marginBottom: 16, fontSize: 13, color: "#f39c12" },
};

export default ST;
